/* Generated By:JJTree: Do not edit this line. ASTDetachedFilterExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.proximati.biprime.server.olapql.language.query;

public
class ASTDetachedFilterExpression extends SimpleNode {
  public ASTDetachedFilterExpression(int id) {
    super(id);
  }

  public ASTDetachedFilterExpression(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(QueryParserVisitor visitor, Object data) throws Exception {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=35cc290dc8fcc431148b6689291faf9a (do not edit this line) */
