/* Generated By:JJTree: Do not edit this line. ASTLevelOrMeasureOrFilter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.proximati.biprime.server.olapql.language.query;

public
class ASTLevelOrMeasureOrFilter extends SimpleNode {
  public ASTLevelOrMeasureOrFilter(int id) {
    super(id);
  }

  public ASTLevelOrMeasureOrFilter(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(QueryParserVisitor visitor, Object data) throws Exception {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0da662018be7d8a7e2134a6a7c2ba8f7 (do not edit this line) */
