/* Generated By:JJTree: Do not edit this line. ASTOrCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.proximati.biprime.server.olapql.language.query;

public
class ASTOrCondition extends SimpleNode {
  public ASTOrCondition(int id) {
    super(id);
  }

  public ASTOrCondition(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(QueryParserVisitor visitor, Object data) throws Exception {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c77f555d3b6f00cbdbac1cb7be149b71 (do not edit this line) */
