/* Generated By:JJTree: Do not edit this line. LevelOrMeasureOrFilter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.proximati.biprime.server.olapql.language.query;

public
class LevelOrMeasureOrFilter extends SimpleNode {
  public LevelOrMeasureOrFilter(int id) {
    super(id);
  }

  public LevelOrMeasureOrFilter(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(QueryParserVisitor visitor, StringBuilder data) {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=305ebe7a53dd826133912c58e54f5378 (do not edit this line) */
