/* Generated By:JavaCC: Do not edit this line. QueryParserTreeConstants.java Version 5.0 */
package br.com.proximati.biprime.server.olapql.language.query;

public interface QueryParserTreeConstants
{
  public int JJTINSTRUCTION = 0;
  public int JJTSELECT = 1;
  public int JJTFILTEREXPRESSION = 2;
  public int JJTAXIS = 3;
  public int JJTVOID = 4;
  public int JJTLEVELORMEASUREORFILTER = 5;
  public int JJTPROPERTYNODE = 6;
  public int JJTLEVEL = 7;
  public int JJTFILTER = 8;
  public int JJTPROPERTY = 9;
  public int JJTCUBE = 10;
  public int JJTDETACHEDFILTEREXPRESSION = 11;
  public int JJTORCONDITION = 12;
  public int JJTANDCONDITION = 13;
  public int JJTCONDITION = 14;
  public int JJTNEGATION = 15;
  public int JJTINEXPRESSION = 16;
  public int JJTLIKEEXPRESSION = 17;
  public int JJTSTARTSWITHEXPRESSION = 18;
  public int JJTENDSWITHEXPRESSION = 19;
  public int JJTCOMPARE = 20;
  public int JJTADDITIVEEXPRESSION = 21;
  public int JJTMULTIPLICATIVEEXPRESSION = 22;
  public int JJTNUMBERLITERAL = 23;
  public int JJTDATELITERAL = 24;
  public int JJTSTRINGLITERAL = 25;


  public String[] jjtNodeName = {
    "Instruction",
    "Select",
    "FilterExpression",
    "Axis",
    "void",
    "LevelOrMeasureOrFilter",
    "PropertyNode",
    "Level",
    "Filter",
    "Property",
    "Cube",
    "DetachedFilterExpression",
    "OrCondition",
    "AndCondition",
    "Condition",
    "Negation",
    "InExpression",
    "LikeExpression",
    "StartsWithExpression",
    "EndsWithExpression",
    "Compare",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "NumberLiteral",
    "DateLiteral",
    "StringLiteral",
  };
}
/* JavaCC - OriginalChecksum=2ab3e114533e896e26d3ba2712d4e170 (do not edit this line) */
