/* Generated By:JavaCC: Do not edit this line. QueryParserTreeConstants.java Version 5.0 */
package br.com.proximati.biprime.server.olapql.language.query;

public interface QueryParserTreeConstants
{
  public int JJTSELECT = 0;
  public int JJTFILTEREXPRESSION = 1;
  public int JJTAXIS = 2;
  public int JJTVOID = 3;
  public int JJTLEVELORMEASUREORFILTER = 4;
  public int JJTPROPERTYNODE = 5;
  public int JJTLEVEL = 6;
  public int JJTFILTER = 7;
  public int JJTPROPERTY = 8;
  public int JJTCUBE = 9;
  public int JJTDETACHEDFILTEREXPRESSION = 10;
  public int JJTORCONDITION = 11;
  public int JJTANDCONDITION = 12;
  public int JJTCONDITION = 13;
  public int JJTNEGATION = 14;
  public int JJTINEXPRESSION = 15;
  public int JJTLIKEEXPRESSION = 16;
  public int JJTSTARTSWITHEXPRESSION = 17;
  public int JJTENDSWITHEXPRESSION = 18;
  public int JJTCOMPARE = 19;
  public int JJTADDITIVEEXPRESSION = 20;
  public int JJTMULTIPLICATIVEEXPRESSION = 21;
  public int JJTNUMBERLITERAL = 22;
  public int JJTDATELITERAL = 23;
  public int JJTSTRINGLITERAL = 24;


  public String[] jjtNodeName = {
    "Select",
    "FilterExpression",
    "Axis",
    "void",
    "LevelOrMeasureOrFilter",
    "PropertyNode",
    "Level",
    "Filter",
    "Property",
    "Cube",
    "DetachedFilterExpression",
    "OrCondition",
    "AndCondition",
    "Condition",
    "Negation",
    "InExpression",
    "LikeExpression",
    "StartsWithExpression",
    "EndsWithExpression",
    "Compare",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "NumberLiteral",
    "DateLiteral",
    "StringLiteral",
  };
}
/* JavaCC - OriginalChecksum=091011fbc848fda173365a21239a5792 (do not edit this line) */
