/* Generated By:JJTree: Do not edit this line. MetadataObject.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.olapql;

public
class MetadataObject extends SimpleNode {
  public MetadataObject(int id) {
    super(id);
  }

  public MetadataObject(OlapQlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dff4e8156fe3cb727e13ede54aff223b (do not edit this line) */
