/* Generated By:JJTree: Do not edit this line. Cube.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.grammar;

public
class Cube extends SimpleNode {
  public Cube(int id) {
    super(id);
  }

  public Cube(OlapQlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=703e189265bd8fa0a1eb160310645d8c (do not edit this line) */
