/* Generated By:JJTree: Do not edit this line. Date.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.grammar;

public
class Date extends SimpleNode {
  public Date(int id) {
    super(id);
  }

  public Date(OlapQlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=acefdfa2bbf6e3c1e3f0c3c476d58457 (do not edit this line) */
