/* Generated By:JJTree: Do not edit this line. Filter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.grammar;

public
class Filter extends SimpleNode {
  public Filter(int id) {
    super(id);
  }

  public Filter(OlapQlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(OlapQlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c6ba1849b0b6234ffeb58b52345c92e7 (do not edit this line) */
