/* Generated By:JJTree: Do not edit this line. Instruction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.grammar;

public
class Instruction extends SimpleNode {
  public Instruction(int id) {
    super(id);
  }

  public Instruction(OlapQlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d91c430049952f98d6fd851ff0edf3d3 (do not edit this line) */
