/* Generated By:JJTree: Do not edit this line. Multiplication.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.grammar;

public
class Multiplication extends SimpleNode {
  public Multiplication(int id) {
    super(id);
  }

  public Multiplication(OlapQlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(OlapQlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0ddb0436f9d705646dac049bb7a8749d (do not edit this line) */
