/* Generated By:JJTree: Do not edit this line. Negation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.grammar;

public
class Negation extends SimpleNode {
  public Negation(int id) {
    super(id);
  }

  public Negation(OlapQlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e79d298ec0d74995cb9320e37b116d8e (do not edit this line) */
