/* Generated By:JavaCC: Do not edit this line. OlapQlParserTreeConstants.java Version 5.0 */
package br.com.bi.model.query.grammar;

public interface OlapQlParserTreeConstants
{
  public int JJTQUERY = 0;
  public int JJTAXIS = 1;
  public int JJTVOID = 2;
  public int JJTMETADATAOBJECT = 3;
  public int JJTCROSSJOIN = 4;
  public int JJTFIRSTSET = 5;
  public int JJTSECONDSET = 6;
  public int JJTCUBE = 7;
  public int JJTFILTER = 8;
  public int JJTDISJUNCTION = 9;
  public int JJTCONJUNCTION = 10;
  public int JJTNEGATION = 11;
  public int JJTCOMPARISON = 12;
  public int JJTRELATIONALOPERATOR = 13;
  public int JJTDATE = 14;
  public int JJTSTRINGLITERAL = 15;
  public int JJTARITHMETICEXPRESSION = 16;
  public int JJTADDITION = 17;
  public int JJTMULTIPLICATION = 18;
  public int JJTNUMBER = 19;


  public String[] jjtNodeName = {
    "Query",
    "Axis",
    "void",
    "MetadataObject",
    "Crossjoin",
    "FirstSet",
    "SecondSet",
    "Cube",
    "Filter",
    "Disjunction",
    "Conjunction",
    "Negation",
    "Comparison",
    "RelationalOperator",
    "Date",
    "StringLiteral",
    "ArithmeticExpression",
    "Addition",
    "Multiplication",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=7a2145cbc770640dcd44c992bf743589 (do not edit this line) */
