/* Generated By:JavaCC: Do not edit this line. OlapQlParserTreeConstants.java Version 5.0 */
package br.com.bi.model.query.grammar;

public interface OlapQlParserTreeConstants
{
  public int JJTINSTRUCTION = 0;
  public int JJTSELECT = 1;
  public int JJTCREATE = 2;
  public int JJTALTER = 3;
  public int JJTDELETE = 4;
  public int JJTAXIS = 5;
  public int JJTVOID = 6;
  public int JJTCROSSJOIN = 7;
  public int JJTMETADATAOBJECT = 8;
  public int JJTCUBE = 9;
  public int JJTFILTER = 10;
  public int JJTDISJUNCTION = 11;
  public int JJTCONJUNCTION = 12;
  public int JJTNEGATION = 13;
  public int JJTCOMPARISON = 14;
  public int JJTRELATIONALOPERATOR = 15;
  public int JJTARITHMETICEXPRESSION = 16;
  public int JJTDATE = 17;
  public int JJTSTRINGLITERAL = 18;
  public int JJTADDITION = 19;
  public int JJTMULTIPLICATION = 20;
  public int JJTNUMBER = 21;


  public String[] jjtNodeName = {
    "Instruction",
    "Select",
    "Create",
    "Alter",
    "Delete",
    "Axis",
    "void",
    "Crossjoin",
    "MetadataObject",
    "Cube",
    "Filter",
    "Disjunction",
    "Conjunction",
    "Negation",
    "Comparison",
    "RelationalOperator",
    "ArithmeticExpression",
    "Date",
    "StringLiteral",
    "Addition",
    "Multiplication",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=5c530323fe0eac0696b8f056d44c55f0 (do not edit this line) */
