/* Generated By:JavaCC: Do not edit this line. FilterParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FilterParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BINARY_LOGIC_OPERATOR = 6;
  /** RegularExpression Id. */
  int RELATIONAL_OPERATOR = 7;
  /** RegularExpression Id. */
  int NOT = 8;
  /** RegularExpression Id. */
  int LPAR = 9;
  /** RegularExpression Id. */
  int RPAR = 10;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 11;
  /** RegularExpression Id. */
  int IDENTIFIER = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<BINARY_LOGIC_OPERATOR>",
    "<RELATIONAL_OPERATOR>",
    "\"n\\u00e3o\"",
    "\"(\"",
    "\")\"",
    "<DECIMAL_LITERAL>",
    "<IDENTIFIER>",
  };

}
