/* Generated By:JJTree: Do not edit this line. Addition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class Addition extends SimpleNode {
  public Addition(int id) {
    super(id);
  }

  public Addition(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1d41d03ca44ae8860bb1fa31fe569081 (do not edit this line) */
