/* Generated By:JJTree: Do not edit this line. Axis.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class Axis extends SimpleNode {
  public Axis(int id) {
    super(id);
  }

  public Axis(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2da148b21109325fc89aead27d13f210 (do not edit this line) */
