/* Generated By:JJTree: Do not edit this line. Comparison.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class Comparison extends SimpleNode {
  public Comparison(int id) {
    super(id);
  }

  public Comparison(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3a912d750f5f150de4b1725a6cadf78c (do not edit this line) */
