/* Generated By:JJTree: Do not edit this line. Crossjoin.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class Crossjoin extends SimpleNode {
  public Crossjoin(int id) {
    super(id);
  }

  public Crossjoin(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8f3b057ee87237aa30283f355578eee6 (do not edit this line) */
