/* Generated By:JJTree: Do not edit this line. Cube.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class Cube extends SimpleNode {
  public Cube(int id) {
    super(id);
  }

  public Cube(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=280f618c7155ee4b3b242d699aed6276 (do not edit this line) */
