/* Generated By:JJTree: Do not edit this line. Disjunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class Disjunction extends SimpleNode {
  public Disjunction(int id) {
    super(id);
  }

  public Disjunction(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c1361065cd2556f7048d2b9e13e9a901 (do not edit this line) */
