/* Generated By:JJTree: Do not edit this line. Instruction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class Instruction extends SimpleNode {
  public Instruction(int id) {
    super(id);
  }

  public Instruction(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9470500622fd1c1d76bdde752a050c38 (do not edit this line) */
