/* Generated By:JJTree: Do not edit this line. LevelOrMeasure.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class LevelOrMeasure extends SimpleNode {
  public LevelOrMeasure(int id) {
    super(id);
  }

  public LevelOrMeasure(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(QueryParserVisitor visitor, StringBuilder data) {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ed3c2419e6810a0d4d507af24d21561d (do not edit this line) */
