/* Generated By:JJTree: Do not edit this line. Measure.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class Measure extends SimpleNode {
  public Measure(int id) {
    super(id);
  }

  public Measure(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2ac74c0579a8dc0b0243b663681005ab (do not edit this line) */
