/* Generated By:JJTree: Do not edit this line. Negation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class Negation extends SimpleNode {
  public Negation(int id) {
    super(id);
  }

  public Negation(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=97e9b0fbb6f6a6ac3515f55aedce250f (do not edit this line) */
