/* Generated By:JavaCC: Do not edit this line. QueryParserTreeConstants.java Version 5.0 */
package br.com.bi.language.query;

public interface QueryParserTreeConstants
{
  public int JJTINSTRUCTION = 0;
  public int JJTSELECT = 1;
  public int JJTAXIS = 2;
  public int JJTVOID = 3;
  public int JJTCROSSJOIN = 4;
  public int JJTMETADATAOBJECT = 5;
  public int JJTCUBE = 6;
  public int JJTFILTEREXPRESSION = 7;
  public int JJTDISJUNCTION = 8;
  public int JJTCONJUNCTION = 9;
  public int JJTNEGATION = 10;
  public int JJTCOMPARISON = 11;
  public int JJTLEVEL = 12;
  public int JJTMEASURE = 13;
  public int JJTFILTER = 14;
  public int JJTPROPERTY = 15;
  public int JJTRELATIONALOPERATOR = 16;
  public int JJTARITHMETICEXPRESSION = 17;
  public int JJTDATE = 18;
  public int JJTSTRINGLITERAL = 19;
  public int JJTADDITION = 20;
  public int JJTMULTIPLICATION = 21;
  public int JJTNUMBER = 22;


  public String[] jjtNodeName = {
    "Instruction",
    "Select",
    "Axis",
    "void",
    "Crossjoin",
    "MetadataObject",
    "Cube",
    "FilterExpression",
    "Disjunction",
    "Conjunction",
    "Negation",
    "Comparison",
    "Level",
    "Measure",
    "Filter",
    "Property",
    "RelationalOperator",
    "ArithmeticExpression",
    "Date",
    "StringLiteral",
    "Addition",
    "Multiplication",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=06bfa29a3410a66cc96c05d3b972e978 (do not edit this line) */
