/* Generated By:JavaCC: Do not edit this line. QueryParserTreeConstants.java Version 5.0 */
package br.com.bi.language.query;

public interface QueryParserTreeConstants
{
  public int JJTINSTRUCTION = 0;
  public int JJTSELECT = 1;
  public int JJTAXIS = 2;
  public int JJTVOID = 3;
  public int JJTCROSSJOIN = 4;
  public int JJTMETADATAOBJECT = 5;
  public int JJTCUBE = 6;
  public int JJTFILTEREXPRESSION = 7;
  public int JJTDISJUNCTION = 8;
  public int JJTCONJUNCTION = 9;
  public int JJTNEGATION = 10;
  public int JJTLEVEL = 11;
  public int JJTMEASURE = 12;
  public int JJTFILTER = 13;
  public int JJTPROPERTY = 14;
  public int JJTRELATIONALOPERATOR = 15;
  public int JJTARITHMETICEXPRESSION = 16;
  public int JJTDATE = 17;
  public int JJTSTRINGLITERAL = 18;
  public int JJTADDITION = 19;
  public int JJTMULTIPLICATION = 20;
  public int JJTNUMBER = 21;


  public String[] jjtNodeName = {
    "Instruction",
    "Select",
    "Axis",
    "void",
    "Crossjoin",
    "MetadataObject",
    "Cube",
    "FilterExpression",
    "Disjunction",
    "Conjunction",
    "Negation",
    "Level",
    "Measure",
    "Filter",
    "Property",
    "RelationalOperator",
    "ArithmeticExpression",
    "Date",
    "StringLiteral",
    "Addition",
    "Multiplication",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=478e1ebbc026103ae1827097e90cd431 (do not edit this line) */
