/* Generated By:JavaCC: Do not edit this line. QueryParserTreeConstants.java Version 5.0 */
package br.com.bi.language.query;

public interface QueryParserTreeConstants
{
  public int JJTINSTRUCTION = 0;
  public int JJTSELECT = 1;
  public int JJTAXIS = 2;
  public int JJTVOID = 3;
  public int JJTLEVELORMEASUREORFILTER = 4;
  public int JJTPROPERTY = 5;
  public int JJTCUBE = 6;
  public int JJTFILTEREXPRESSION = 7;
  public int JJTDISJUNCTION = 8;
  public int JJTCONJUNCTION = 9;
  public int JJTNEGATION = 10;
  public int JJTCOMPARISON = 11;
  public int JJTLEVEL = 12;
  public int JJTFILTER = 13;
  public int JJTRELATIONALOPERATOR = 14;
  public int JJTARITHMETICEXPRESSION = 15;
  public int JJTDATE = 16;
  public int JJTSTRINGLITERAL = 17;
  public int JJTADDITION = 18;
  public int JJTMULTIPLICATION = 19;
  public int JJTNUMBER = 20;


  public String[] jjtNodeName = {
    "Instruction",
    "Select",
    "Axis",
    "void",
    "LevelOrMeasureOrFilter",
    "Property",
    "Cube",
    "FilterExpression",
    "Disjunction",
    "Conjunction",
    "Negation",
    "Comparison",
    "Level",
    "Filter",
    "RelationalOperator",
    "ArithmeticExpression",
    "Date",
    "StringLiteral",
    "Addition",
    "Multiplication",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=2dde8a3ebc24c124a3c9f5cdfed551cb (do not edit this line) */
