/* Generated By:JJTree: Do not edit this line. Select.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class Select extends SimpleNode {
  public Select(int id) {
    super(id);
  }

  public Select(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e5543d07f63ebb36458071b87d2eb429 (do not edit this line) */
