/* Generated By:JJTree: Do not edit this line. Comparison.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.grammar;

public
class Comparison extends SimpleNode {
  public Comparison(int id) {
    super(id);
  }

  public Comparison(OlapQlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=897838183e3c6d085b5022dc6dc871a2 (do not edit this line) */
