/* Generated By:JJTree: Do not edit this line. Conjunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.grammar;

public
class Conjunction extends SimpleNode {
  public Conjunction(int id) {
    super(id);
  }

  public Conjunction(OlapQlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2b0bd773a78f37cf29ac423466a523bc (do not edit this line) */
