/* Generated By:JJTree: Do not edit this line. Cube.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.grammar;

public
class Cube extends SimpleNode {
  public Cube(int id) {
    super(id);
  }

  public Cube(OlapQlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(OlapQlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0a5004dab099d13e58148f6cf59a2ad0 (do not edit this line) */
