/* Generated By:JJTree: Do not edit this line. Disjunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.grammar;

public
class Disjunction extends SimpleNode {
  public Disjunction(int id) {
    super(id);
  }

  public Disjunction(OlapQlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=157078f57d4c7094aa81ec507cec6644 (do not edit this line) */
