/* Generated By:JJTree: Do not edit this line. Instruction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.grammar;

public
class Instruction extends SimpleNode {
  public Instruction(int id) {
    super(id);
  }

  public Instruction(OlapQlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(OlapQlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e788fbcde2c2f139e37de3146b0968bb (do not edit this line) */
