/* Generated By:JavaCC: Do not edit this line. OlapQlParserTreeConstants.java Version 5.0 */
package br.com.bi.model.query.grammar;

public interface OlapQlParserTreeConstants
{
  public int JJTQUERY = 0;
  public int JJTCOLUMNS = 1;
  public int JJTROWS = 2;
  public int JJTVOID = 3;
  public int JJTMETADATAOBJECT = 4;
  public int JJTCROSSJOIN = 5;
  public int JJTCROSSJOINFIRSTPARAM = 6;
  public int JJTCROSSJOINSECONDPARAM = 7;
  public int JJTCUBE = 8;
  public int JJTFILTER = 9;
  public int JJTDISJUNCTION = 10;
  public int JJTCONJUNCTION = 11;
  public int JJTNEGATION = 12;


  public String[] jjtNodeName = {
    "Query",
    "Columns",
    "Rows",
    "void",
    "MetadataObject",
    "Crossjoin",
    "CrossjoinFirstParam",
    "CrossjoinSecondParam",
    "Cube",
    "Filter",
    "Disjunction",
    "Conjunction",
    "Negation",
  };
}
/* JavaCC - OriginalChecksum=6ed3c371f3f46acf91a7c9fd9a4ced66 (do not edit this line) */
