/* Generated By:JavaCC: Do not edit this line. OlapQlParserTreeConstants.java Version 5.0 */
package br.com.bi.model.query.grammar;

public interface OlapQlParserTreeConstants
{
  public int JJTQUERY = 0;
  public int JJTAXISSPECIFICATION = 1;
  public int JJTVOID = 2;
  public int JJTMETADATAOBJECT = 3;
  public int JJTCROSSJOIN = 4;
  public int JJTFIRSTSET = 5;
  public int JJTSECONDSET = 6;
  public int JJTCUBE = 7;
  public int JJTFILTER = 8;
  public int JJTDISJUNCTION = 9;
  public int JJTCONJUNCTION = 10;
  public int JJTNEGATION = 11;
  public int JJTCOMPARISON = 12;
  public int JJTRELATIONALOPERATOR = 13;
  public int JJTMULTIPLICATON = 14;
  public int JJTNUMBER = 15;


  public String[] jjtNodeName = {
    "Query",
    "AxisSpecification",
    "void",
    "MetadataObject",
    "Crossjoin",
    "FirstSet",
    "SecondSet",
    "Cube",
    "Filter",
    "Disjunction",
    "Conjunction",
    "Negation",
    "Comparison",
    "RelationalOperator",
    "Multiplicaton",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=3241bccb28c7905ec7713d869b06a40a (do not edit this line) */
