/* Generated By:JJTree: Do not edit this line. RelationalOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.grammar;

public
class RelationalOperator extends SimpleNode {
  public RelationalOperator(int id) {
    super(id);
  }

  public RelationalOperator(OlapQlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=522eb3cd4a37fc6ed0e0815a9299ca29 (do not edit this line) */
