/* Generated By:JJTree: Do not edit this line. ASTEndsWithExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.proximati.biprime.server.olapql.language.query;

public
class ASTEndsWithExpression extends SimpleNode {
  public ASTEndsWithExpression(int id) {
    super(id);
  }

  public ASTEndsWithExpression(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(QueryParserVisitor visitor, Object data) throws Exception {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e6c466c855173f1aefb1e1fb029c8d12 (do not edit this line) */
