/* Generated By:JJTree: Do not edit this line. ASTStartsWithExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.proximati.biprime.server.olapql.language.query;

public
class ASTStartsWithExpression extends SimpleNode {
  public ASTStartsWithExpression(int id) {
    super(id);
  }

  public ASTStartsWithExpression(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(QueryParserVisitor visitor, Object data) throws Exception {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=269babf1a330903aae990603c6e10597 (do not edit this line) */
