/* Generated By:JavaCC: Do not edit this line. QueryParserVisitor.java Version 5.0 */
package br.com.proximati.biprime.server.olapql.language.query;

public interface QueryParserVisitor
{
  public void visit(SimpleNode node, StringBuilder data) throws Exception;
  public void visit(ASTSelect node, StringBuilder data) throws Exception;
  public void visit(ASTFilterExpression node, StringBuilder data) throws Exception;
  public void visit(ASTAxis node, StringBuilder data) throws Exception;
  public void visit(ASTLevelOrMeasureOrFilter node, StringBuilder data) throws Exception;
  public void visit(ASTPropertyNode node, StringBuilder data) throws Exception;
  public void visit(ASTLevel node, StringBuilder data) throws Exception;
  public void visit(ASTFilter node, StringBuilder data) throws Exception;
  public void visit(ASTProperty node, StringBuilder data) throws Exception;
  public void visit(ASTCube node, StringBuilder data) throws Exception;
  public void visit(ASTDetachedFilterExpression node, StringBuilder data) throws Exception;
  public void visit(ASTOrCondition node, StringBuilder data) throws Exception;
  public void visit(ASTAndCondition node, StringBuilder data) throws Exception;
  public void visit(ASTCondition node, StringBuilder data) throws Exception;
  public void visit(ASTNegation node, StringBuilder data) throws Exception;
  public void visit(ASTInExpression node, StringBuilder data) throws Exception;
  public void visit(ASTLikeExpression node, StringBuilder data) throws Exception;
  public void visit(ASTStartsWithExpression node, StringBuilder data) throws Exception;
  public void visit(ASTEndsWithExpression node, StringBuilder data) throws Exception;
  public void visit(ASTCompare node, StringBuilder data) throws Exception;
  public void visit(ASTAdditiveExpression node, StringBuilder data) throws Exception;
  public void visit(ASTMultiplicativeExpression node, StringBuilder data) throws Exception;
  public void visit(ASTNumberLiteral node, StringBuilder data) throws Exception;
  public void visit(ASTDateLiteral node, StringBuilder data) throws Exception;
  public void visit(ASTStringLiteral node, StringBuilder data) throws Exception;
}
/* JavaCC - OriginalChecksum=a436c74f05264de2fd17c90b1534ac87 (do not edit this line) */
