/* Generated By:JavaCC: Do not edit this line. FilterParserTreeConstants.java Version 5.0 */
package br.com.bi.olapql.language.filter;

public interface FilterParserTreeConstants
{
  public int JJTFILTEREXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTDISJUNCTION = 2;
  public int JJTCONJUNCTION = 3;
  public int JJTNEGATION = 4;
  public int JJTCOMPARISON = 5;
  public int JJTLEVEL = 6;
  public int JJTFILTER = 7;
  public int JJTPROPERTY = 8;
  public int JJTRELATIONALOPERATOR = 9;
  public int JJTARITHMETICEXPRESSION = 10;
  public int JJTDATE = 11;
  public int JJTSTRINGLITERAL = 12;
  public int JJTADDITION = 13;
  public int JJTMULTIPLICATION = 14;
  public int JJTNUMBER = 15;


  public String[] jjtNodeName = {
    "FilterExpression",
    "void",
    "Disjunction",
    "Conjunction",
    "Negation",
    "Comparison",
    "Level",
    "Filter",
    "Property",
    "RelationalOperator",
    "ArithmeticExpression",
    "Date",
    "StringLiteral",
    "Addition",
    "Multiplication",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=3e15dc403e9638fe92b402b1882075ef (do not edit this line) */
