/* Generated By:JJTree&JavaCC: Do not edit this line. FilterParserConstants.java */
package br.com.bi.olapql.language.filter;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FilterParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RELATIONAL_OPERATOR = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int AND = 8;
  /** RegularExpression Id. */
  int OR = 9;
  /** RegularExpression Id. */
  int DOT = 10;
  /** RegularExpression Id. */
  int PLUS = 11;
  /** RegularExpression Id. */
  int MINUS = 12;
  /** RegularExpression Id. */
  int MULT = 13;
  /** RegularExpression Id. */
  int DIV = 14;
  /** RegularExpression Id. */
  int LBRA = 15;
  /** RegularExpression Id. */
  int RBRA = 16;
  /** RegularExpression Id. */
  int DATE = 17;
  /** RegularExpression Id. */
  int METADATA_OBJECT_NAME = 18;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 19;
  /** RegularExpression Id. */
  int EXPONENT = 20;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 21;
  /** RegularExpression Id. */
  int STRING_LITERAL = 22;
  /** RegularExpression Id. */
  int CHAR = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<RELATIONAL_OPERATOR>",
    "\"n\\u00e3o\"",
    "\"e\"",
    "\"ou\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "<DATE>",
    "<METADATA_OBJECT_NAME>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
    "<CHAR>",
    "\"(\"",
    "\")\"",
  };

}
