/* Generated By:JavaCC: Do not edit this line. FilterParserTreeConstants.java Version 5.0 */
package br.com.bi.language.measure;

public interface FilterParserTreeConstants
{
  public int JJTMEASUREEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTADDITION = 2;
  public int JJTMULTIPLICATION = 3;
  public int JJTAGGREGATION = 4;
  public int JJTCOLUMN = 5;
  public int JJTNUMBER = 6;


  public String[] jjtNodeName = {
    "MeasureExpression",
    "void",
    "Addition",
    "Multiplication",
    "Aggregation",
    "Column",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=61fda6e7c1bba33809a421041f75561c (do not edit this line) */
