/* Generated By:JavaCC: Do not edit this line. FilterParserVisitor.java Version 5.0 */
package br.com.bi.language.filter;

public interface FilterParserVisitor
{
  public void visit(SimpleNode node, StringBuilder data);
  public void visit(FilterExpression node, StringBuilder data);
  public void visit(Disjunction node, StringBuilder data);
  public void visit(Conjunction node, StringBuilder data);
  public void visit(Negation node, StringBuilder data);
  public void visit(Comparison node, StringBuilder data);
  public void visit(Measure node, StringBuilder data);
  public void visit(Level node, StringBuilder data);
  public void visit(Filter node, StringBuilder data);
  public void visit(Property node, StringBuilder data);
  public void visit(RelationalOperator node, StringBuilder data);
  public void visit(ArithmeticExpression node, StringBuilder data);
  public void visit(Date node, StringBuilder data);
  public void visit(StringLiteral node, StringBuilder data);
  public void visit(Addition node, StringBuilder data);
  public void visit(Multiplication node, StringBuilder data);
  public void visit(Number node, StringBuilder data);
}
/* JavaCC - OriginalChecksum=8416d0f5984b8c707202e395571a3d02 (do not edit this line) */
