/* Generated By:JavaCC: Do not edit this line. FilterParserTreeConstants.java Version 5.0 */
package br.com.bi.language.filter;

public interface FilterParserTreeConstants
{
  public int JJTFILTEREXPRESSION = 0;
  public int JJTDISJUNCTION = 1;
  public int JJTCONJUNCTION = 2;
  public int JJTVOID = 3;
  public int JJTNEGATION = 4;
  public int JJTCOMPARISON = 5;
  public int JJTMEASURE = 6;
  public int JJTLEVELORMEASURE = 7;
  public int JJTFILTER = 8;
  public int JJTPROPERTY = 9;
  public int JJTRELATIONALOPERATOR = 10;
  public int JJTARITHMETICEXPRESSION = 11;
  public int JJTDATE = 12;
  public int JJTSTRINGLITERAL = 13;
  public int JJTADDITION = 14;
  public int JJTMULTIPLICATION = 15;
  public int JJTNUMBER = 16;


  public String[] jjtNodeName = {
    "FilterExpression",
    "Disjunction",
    "Conjunction",
    "void",
    "Negation",
    "Comparison",
    "Measure",
    "LevelOrMeasure",
    "Filter",
    "Property",
    "RelationalOperator",
    "ArithmeticExpression",
    "Date",
    "StringLiteral",
    "Addition",
    "Multiplication",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=ad67bda9ceddf02685c6519df5b8406a (do not edit this line) */
