/* Generated By:JavaCC: Do not edit this line. FilterParserTreeConstants.java Version 5.0 */
package br.com.bi.language.filter;

public interface FilterParserTreeConstants
{
  public int JJTFILTEREXPRESSION = 0;
  public int JJTDISJUNCTION = 1;
  public int JJTCONJUNCTION = 2;
  public int JJTVOID = 3;
  public int JJTNEGATION = 4;
  public int JJTMEASURE = 5;
  public int JJTLEVEL = 6;
  public int JJTFILTER = 7;
  public int JJTPROPERTY = 8;
  public int JJTRELATIONALOPERATOR = 9;
  public int JJTARITHMETICEXPRESSION = 10;
  public int JJTDATE = 11;
  public int JJTSTRINGLITERAL = 12;
  public int JJTADDITION = 13;
  public int JJTMULTIPLICATION = 14;
  public int JJTNUMBER = 15;


  public String[] jjtNodeName = {
    "FilterExpression",
    "Disjunction",
    "Conjunction",
    "void",
    "Negation",
    "Measure",
    "Level",
    "Filter",
    "Property",
    "RelationalOperator",
    "ArithmeticExpression",
    "Date",
    "StringLiteral",
    "Addition",
    "Multiplication",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=e26ee836d521f79cd8427aebb6f198bb (do not edit this line) */
