/* Generated By:JJTree: Do not edit this line. ASTColumn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.proximati.biprime.server.olapql.language.measure;

public
class ASTColumn extends SimpleNode {
  public ASTColumn(int id) {
    super(id);
  }

  public ASTColumn(MeasureParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(MeasureParserVisitor visitor, StringBuilder data) throws Exception {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=df02f37c62269d18b89f2e30859111e3 (do not edit this line) */
