/* Generated By:JJTree: Do not edit this line. ASTMeasureExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.proximati.biprime.server.olapql.language.measure;

public
class ASTMeasureExpression extends SimpleNode {
  public ASTMeasureExpression(int id) {
    super(id);
  }

  public ASTMeasureExpression(MeasureParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(MeasureParserVisitor visitor, StringBuilder data) throws Exception {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7f195bfca7a1bfc781e12c8f45de185a (do not edit this line) */
