/* Generated By:JavaCC: Do not edit this line. MeasureParserTreeConstants.java Version 5.0 */
package br.com.proximati.biprime.server.olapql.language.measure;

public interface MeasureParserTreeConstants
{
  public int JJTMEASUREEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTADDITION = 2;
  public int JJTMULTIPLICATION = 3;
  public int JJTMEASURE = 4;
  public int JJTAGGREGATION = 5;
  public int JJTCOLUMN = 6;
  public int JJTNUMBER = 7;


  public String[] jjtNodeName = {
    "MeasureExpression",
    "void",
    "Addition",
    "Multiplication",
    "Measure",
    "Aggregation",
    "Column",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=73a0fc6cc7b9243062a8944924a0c2e4 (do not edit this line) */
