/* Generated By:JJTree&JavaCC: Do not edit this line. MeasureParserConstants.java */
package br.com.proximati.biprime.server.olapql.language.measure;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MeasureParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RELATIONAL_OPERATOR = 6;
  /** RegularExpression Id. */
  int AGGREGATOR = 7;
  /** RegularExpression Id. */
  int IDENTIFIER = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int MULT = 11;
  /** RegularExpression Id. */
  int DIV = 12;
  /** RegularExpression Id. */
  int LBRA = 13;
  /** RegularExpression Id. */
  int RBRA = 14;
  /** RegularExpression Id. */
  int DATE = 15;
  /** RegularExpression Id. */
  int METADATA_OBJECT_NAME = 16;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 17;
  /** RegularExpression Id. */
  int EXPONENT = 18;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 19;
  /** RegularExpression Id. */
  int STRING_LITERAL = 20;
  /** RegularExpression Id. */
  int CHAR = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<RELATIONAL_OPERATOR>",
    "<AGGREGATOR>",
    "<IDENTIFIER>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "<DATE>",
    "<METADATA_OBJECT_NAME>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
    "<CHAR>",
    "\"(\"",
    "\")\"",
  };

}
