/* Generated By:JavaCC: Do not edit this line. FilterParserVisitor.java Version 5.0 */
package br.com.bi.olapql.language.filter;

public interface FilterParserVisitor
{
  public void visit(SimpleNode node, StringBuilder data);
  public void visit(FilterExpression node, StringBuilder data);
  public void visit(Disjunction node, StringBuilder data);
  public void visit(Conjunction node, StringBuilder data);
  public void visit(Negation node, StringBuilder data);
  public void visit(Comparison node, StringBuilder data);
  public void visit(Level node, StringBuilder data);
  public void visit(Filter node, StringBuilder data);
  public void visit(Property node, StringBuilder data);
  public void visit(RelationalOperator node, StringBuilder data);
  public void visit(ArithmeticExpression node, StringBuilder data);
  public void visit(Date node, StringBuilder data);
  public void visit(StringLiteral node, StringBuilder data);
  public void visit(Addition node, StringBuilder data);
  public void visit(Multiplication node, StringBuilder data);
  public void visit(Number node, StringBuilder data);
}
/* JavaCC - OriginalChecksum=0a2b3d1d9a2f3ac62aed19fe02b91ee3 (do not edit this line) */
