/* Generated By:JJTree: Do not edit this line. ArithmeticExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.olapql;

public
class ArithmeticExpression extends SimpleNode {
  public ArithmeticExpression(int id) {
    super(id);
  }

  public ArithmeticExpression(OlapQlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=71ac40f5957b1937384581e93ed9d330 (do not edit this line) */
