/* Generated By:JJTree: Do not edit this line. Filter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.olapql;

public
class Filter extends SimpleNode {
  public Filter(int id) {
    super(id);
  }

  public Filter(OlapQlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d570d28ee039a3c4e45d5a4bafca1bb8 (do not edit this line) */
