/* Generated By:JJTree: Do not edit this line. RelationalOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.model.query.olapql;

public
class RelationalOperator extends SimpleNode {
  public RelationalOperator(int id) {
    super(id);
  }

  public RelationalOperator(OlapQlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8eb95622d16b2c5bbdf3733bbd1c015c (do not edit this line) */
