/* Generated By:JavaCC: Do not edit this line. FilterParserVisitor.java Version 5.0 */
package br.com.bi.language.measure;

public interface FilterParserVisitor
{
  public void visit(SimpleNode node, StringBuilder data);
  public void visit(MeasureExpression node, StringBuilder data);
  public void visit(Addition node, StringBuilder data);
  public void visit(Multiplication node, StringBuilder data);
  public void visit(Aggregation node, StringBuilder data);
  public void visit(Column node, StringBuilder data);
  public void visit(Number node, StringBuilder data);
}
/* JavaCC - OriginalChecksum=26edf0f114fb1315ee58893bbc3e0db0 (do not edit this line) */
