/* Generated By:JavaCC: Do not edit this line. MeasureParserVisitor.java Version 5.0 */
package br.com.bi.language.measure;

public interface MeasureParserVisitor
{
  public void visit(SimpleNode node, StringBuilder data);
  public void visit(MeasureExpression node, StringBuilder data);
  public void visit(Addition node, StringBuilder data);
  public void visit(Multiplication node, StringBuilder data);
  public void visit(Measure node, StringBuilder data);
  public void visit(Aggregation node, StringBuilder data);
  public void visit(Column node, StringBuilder data);
  public void visit(Number node, StringBuilder data);
}
/* JavaCC - OriginalChecksum=06566fdf633117a68675c3f1b720b64a (do not edit this line) */
