/* Generated By:JJTree: Do not edit this line. ArithmeticExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class ArithmeticExpression extends SimpleNode {
  public ArithmeticExpression(int id) {
    super(id);
  }

  public ArithmeticExpression(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=14b8c95442f9b1098346409f6bdcd1a5 (do not edit this line) */
