/* Generated By:JJTree: Do not edit this line. FilterExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class FilterExpression extends SimpleNode {
  public FilterExpression(int id) {
    super(id);
  }

  public FilterExpression(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f822221df10bde4d42ade62425e8a7a0 (do not edit this line) */
