/* Generated By:JJTree: Do not edit this line. Filter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class Filter extends SimpleNode {
  public Filter(int id) {
    super(id);
  }

  public Filter(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1e687e519e45fe8dd08c2ffe209b08ce (do not edit this line) */
