/* Generated By:JJTree: Do not edit this line. Level.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class Level extends SimpleNode {
  public Level(int id) {
    super(id);
  }

  public Level(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b95baad3ae00ec64b36ebd565ef4560 (do not edit this line) */
