/* Generated By:JJTree: Do not edit this line. Number.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class Number extends SimpleNode {
  public Number(int id) {
    super(id);
  }

  public Number(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7349e3a2678fa9047b957ef30806bc31 (do not edit this line) */
