/* Generated By:JavaCC: Do not edit this line. QueryParserTreeConstants.java Version 5.0 */
package br.com.bi.language.query;

public interface QueryParserTreeConstants
{
  public int JJTINSTRUCTION = 0;
  public int JJTSELECT = 1;
  public int JJTAXIS = 2;
  public int JJTVOID = 3;
  public int JJTSET = 4;
  public int JJTLEVELORMEASUREORFILTER = 5;
  public int JJTPROPERTY = 6;
  public int JJTCROSSJOIN = 7;
  public int JJTCUBE = 8;
  public int JJTFILTEREXPRESSION = 9;
  public int JJTDISJUNCTION = 10;
  public int JJTCONJUNCTION = 11;
  public int JJTNEGATION = 12;
  public int JJTCOMPARISON = 13;
  public int JJTLEVELORMEASURE = 14;
  public int JJTMEASURE = 15;
  public int JJTFILTER = 16;
  public int JJTRELATIONALOPERATOR = 17;
  public int JJTARITHMETICEXPRESSION = 18;
  public int JJTDATE = 19;
  public int JJTSTRINGLITERAL = 20;
  public int JJTADDITION = 21;
  public int JJTMULTIPLICATION = 22;
  public int JJTNUMBER = 23;


  public String[] jjtNodeName = {
    "Instruction",
    "Select",
    "Axis",
    "void",
    "Set",
    "LevelOrMeasureOrFilter",
    "Property",
    "Crossjoin",
    "Cube",
    "FilterExpression",
    "Disjunction",
    "Conjunction",
    "Negation",
    "Comparison",
    "LevelOrMeasure",
    "Measure",
    "Filter",
    "RelationalOperator",
    "ArithmeticExpression",
    "Date",
    "StringLiteral",
    "Addition",
    "Multiplication",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=c18bc0b8bd6bb0bf68f8bb02a1143afd (do not edit this line) */
