/* Generated By:JJTree: Do not edit this line. StringLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.language.query;

public
class StringLiteral extends SimpleNode {
  public StringLiteral(int id) {
    super(id);
  }

  public StringLiteral(QueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2d5fd18d7b30b12f88d51924811ea4b5 (do not edit this line) */
