/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bi.olapql.language.query.translator;

import br.com.bi.olapql.language.filter.translator.FilterSqlTranslator;
import br.com.bi.olapql.language.measure.translator.MeasureSqlTranslator;
import br.com.bi.olapql.language.query.Addition;
import br.com.bi.olapql.language.query.Axis;
import br.com.bi.olapql.language.query.Conjunction;
import br.com.bi.olapql.language.query.Cube;
import br.com.bi.olapql.language.query.Date;
import br.com.bi.olapql.language.query.Disjunction;
import br.com.bi.olapql.language.query.Filter;
import br.com.bi.olapql.language.query.FilterExpression;
import br.com.bi.olapql.language.query.LevelOrMeasureOrFilter;
import br.com.bi.olapql.language.query.Multiplication;
import br.com.bi.olapql.language.query.Negation;
import br.com.bi.olapql.language.query.Node;
import br.com.bi.olapql.language.query.Property;
import br.com.bi.olapql.language.query.PropertyNode;
import br.com.bi.olapql.language.query.RelationalOperator;
import br.com.bi.olapql.language.query.Select;
import br.com.bi.olapql.language.query.SimpleNode;
import br.com.bi.olapql.language.query.StringLiteral;
import br.com.bi.olapql.language.utils.TranslationUtils;
import br.com.bi.model.Application;
import br.com.bi.model.entity.metadata.CubeLevel;
import br.com.bi.model.entity.metadata.Level;
import br.com.bi.model.entity.metadata.Metadata;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import java.util.Stack;

/**
 *
 * @author luiz
 */
public class QuerySqlTranslator extends AbstractQueryVisitor {

    private br.com.bi.model.entity.metadata.Cube cube;
    private QueryMetadataExtractor extractor = new QueryMetadataExtractor();
    private Stack<Integer> nodeCoordinates = new Stack<Integer>();
    // =================================================
    // variables used in coordinates calculating process
    // =================================================
    /**
     * List used to put the nodes in the order that they appear in the query axis.
     * It's used on translation of "group by" expression, this is because it's ordered.
     */
    private List<Node> axisNodeList = new ArrayList<Node>();
    private Map<Node, Metadata> axisNodeMetadataMap = new HashMap<Node, Metadata>();
    private Map<Node, String> axisNodeCoordinateMap = new HashMap<Node, String>();

    @Override
    public void visit(Select node, StringBuilder data) {
        cube = Application.getCubeDao().findByName(TranslationUtils.extractName(((SimpleNode) node.jjtGetChild(2)).jjtGetValue().toString()));

        extractor.visit(node, data);

        data.append("select ");

        visitChildren(node, data);

        if (!axisNodeMetadataMap.isEmpty()) {

            StringBuilder groupBy = new StringBuilder();

            for (Node n : axisNodeList) {
                Metadata metadata = axisNodeMetadataMap.get(n);

                if (metadata instanceof br.com.bi.model.entity.metadata.Level
                        || metadata instanceof br.com.bi.model.entity.metadata.Property) {
                    groupBy.append(axisNodeCoordinateMap.get(n)).append(", ");
                }
            }

            if (groupBy.length() > 0) {
                groupBy.delete(groupBy.length() - 2, groupBy.length());

                data.append(" group by ").append(groupBy);
            }
        }
    }

    @Override
    public void visit(Cube node, StringBuilder data) {
        // delete last comma generated by axis translation
        data.delete(data.length() - 2, data.length());

        data.append(" from ");

        Set<String> tables = new HashSet<String>();

        tables.add(TranslationUtils.tableExpression(cube.getSchemaName(), cube.getTableName()));

        for (Level level : levelsPresent()) {
            for (Level lowerLevel : level.getLowerLevels()) {
                tables.add(TranslationUtils.tableExpression(lowerLevel.getSchemaName(), lowerLevel.getTableName()));
            }
        }

        for (String table : tables) {
            data.append(table).append(", ");
        }

        if (!tables.isEmpty()) {
            data.delete(data.length() - 2, data.length());
        }

        data.append(" where ");

        whereExpression(data);
    }

    @Override
    public void visit(FilterExpression node, StringBuilder data) {
        data.append(" and ");
        visitChildren(node, data);
    }

    @Override
    public void visit(Disjunction node, StringBuilder data) {
        visitOperation(node, "or", data);
    }

    @Override
    public void visit(Conjunction node, StringBuilder data) {
        visitOperation(node, "and", data);
    }

    @Override
    public void visit(Negation node, StringBuilder data) {
        if (data.charAt(data.length() - 1) != ' ') {
            data.append(" not");
        } else {
            data.append("not ");
        }

        visit(node.jjtGetChild(0), data);
    }

    @Override
    public void visit(br.com.bi.olapql.language.query.Level node, StringBuilder data) {
        br.com.bi.model.entity.metadata.Level level =
                extractor.getAllReferencedMetadata().getLevel(node.jjtGetValue().toString());

        data.append(translateLevel(level));
    }

    @Override
    public void visit(Filter node, StringBuilder data) {
        FilterSqlTranslator translator = new FilterSqlTranslator(this.cube);
        String filterTranslation = translator.translate(node.jjtGetValue().toString());
        data.append(filterTranslation);
    }

    @Override
    public void visit(PropertyNode node, StringBuilder data) {
        nodeCoordinates.push(childIndex(node));

        br.com.bi.model.entity.metadata.Property property =
                extractor.getAllReferencedMetadata().getProperty(node.jjtGetValue().toString());

        registrateAxisNode(node, property);
                
        data.append(translateProperty(property));
        data.append(" as ").append(axisNodeCoordinateMap.get(node));
        data.append(", ");

        super.visit(node, data);
        nodeCoordinates.pop();
    }

    @Override
    public void visit(Property node, StringBuilder data) {
        br.com.bi.model.entity.metadata.Property property =
                extractor.getAllReferencedMetadata().getProperty(node.jjtGetValue().toString());

        data.append(translateProperty(property));
    }

    @Override
    public void visit(RelationalOperator node, StringBuilder data) {
        data.append(" ").append(node.jjtGetValue()).append(" ");
    }

    @Override
    public void visit(Date node, StringBuilder data) {
        data.append(node.jjtGetValue());
    }

    @Override
    public void visit(StringLiteral node, StringBuilder data) {
        data.append(node.jjtGetValue());
    }

    @Override
    public void visit(Addition node, StringBuilder data) {
        visitOperation(node, data);
    }

    @Override
    public void visit(Multiplication node, StringBuilder data) {
        visitOperation(node, data);
    }

    @Override
    public void visit(br.com.bi.olapql.language.query.Number node, StringBuilder data) {
        data.append(node.jjtGetValue());
    }

    @Override
    public void visit(Axis node, StringBuilder data) {
        if (node.jjtGetValue().toString().equals("ROWS")) {
            nodeCoordinates.push(0);
        } else {
            nodeCoordinates.push(1);
        }

        super.visit(node, data);

        nodeCoordinates.pop();
    }

    @Override
    public void visit(LevelOrMeasureOrFilter node, StringBuilder data) {
        nodeCoordinates.push(childIndex(node));

        StringBuilder sb = new StringBuilder();

        br.com.bi.model.entity.metadata.Metadata metadata =
                extractor.getAllReferencedMetadata().getMeasure(node.jjtGetValue().toString());

        if (metadata != null) {
            MeasureSqlTranslator translator = new MeasureSqlTranslator(cube);

            sb.append(translator.translate(node.jjtGetValue().toString()));
        } else {
            metadata = extractor.getAllReferencedMetadata().getLevel(node.jjtGetValue().toString());

            if (metadata != null) {
                data.append(TranslationUtils.columnExpression(((br.com.bi.model.entity.metadata.Level) metadata).getTableName(), ((Level) metadata).getCodeProperty().getColumnName()));
            } else {
                metadata = extractor.getAllReferencedMetadata().getFilter(node.jjtGetValue().toString());

                FilterSqlTranslator translator = new FilterSqlTranslator(cube);

                sb.append("case when ").append(translator.translate(((br.com.bi.model.entity.metadata.Filter) metadata).getExpression())).append(" then 1 else 0 end");
            }
        }

        registrateAxisNode(node, metadata);
        
        data.append(sb).append(" as ").append(axisNodeCoordinateMap.get(node)).append(", ");

        super.visit(node, data);
        nodeCoordinates.pop();
    }

    private void visitOperation(SimpleNode node, StringBuilder data) {
        visitOperation(node, node.jjtGetValue().toString(), data);
    }

    private void visitOperation(SimpleNode node, String op, StringBuilder data) {
        data.append("(");

        for (int i = 0; i < node.jjtGetNumChildren(); i++) {
            visit(node.jjtGetChild(i), data);
            if (i < node.jjtGetNumChildren() - 1) {
                data.append(" ").append(op).append(" ");
            }
        }

        data.append(")");
    }

    // ==========================
    // ====== Utilitários =======
    // ==========================
    /**
     * Retorna os níveis presentes na consulta, seja explicitamente em um nó, ou indiretamente
     * através de um nó filtro, ou filtro de métrica, ou ainda filtro na consulta.
     * @param query
     * @return
     */
    private List<Level> levelsPresent() {
        List<Level> levels = new ArrayList<Level>();

        for (Entry<String, Metadata> entry :
                extractor.getAllReferencedMetadata().getInternalMap().entrySet()) {
            if (entry.getValue() instanceof Level) {
                levels.add((Level) entry.getValue());
            } else if (entry.getValue() instanceof br.com.bi.model.entity.metadata.Property) {
                levels.add(((br.com.bi.model.entity.metadata.Property) entry.getValue()).getLevel());
            }
        }

        return levels;
    }

    /**
     * Produz a cláusula WHERE da consulta, baseado nos joins resultantes das referências
     * para os níveis da consulta.
     * @return
     */
    private String whereExpression(StringBuilder data) {
        List<String> joins = new ArrayList<String>();

        List<Level> levels = levelsPresent();

        // do nível mais alto vai descendo e adicionando os joins até chegar o nível
        // mais baixo e assim juntá-lo ao cubo
        for (Level level : levels) {
            List<Level> lowerLevels = level.getLowerLevels();

            for (int i = 0; i < lowerLevels.size(); i++) {
                // de duas em duas colunas, coloca o join na lista
                if (i > 0 & (i + 1) % 2 == 0) {
                    String upperColumn = TranslationUtils.columnExpression(lowerLevels.get(i - 1).getTableName(), lowerLevels.get(i - 1).getCodeProperty().getColumnName());

                    String thisColumn = TranslationUtils.columnExpression(lowerLevels.get(i).getTableName(), lowerLevels.get(i).getUpperLevelJoinColumn());

                    joins.add(thisColumn + " = " + upperColumn);
                }
            }

            // o nível mais baixo (cujo índice é o maior) é o nível que faz junção com o cubo,
            // e indiretamente liga todos os níveis superiores também.
            Collections.sort(lowerLevels, new Comparator<Level>()          {

                public int compare(Level level1, Level level2) {
                    return Integer.valueOf(level1.getIndice()).compareTo(Integer.valueOf(level2.getIndice()));
                }
            });

            Level lowestLevel = lowerLevels.get(lowerLevels.size() - 1);

            for (CubeLevel cubeLevel : cube.getCubeLevelList()) {
                if (cubeLevel.getLevel().getId() == lowestLevel.getId()) {
                    joins.add(TranslationUtils.columnExpression(cube.getTableName(), cubeLevel.getJoinColumn()) + " = " + TranslationUtils.columnExpression(lowestLevel.getTableName(), lowestLevel.getCodeProperty().getColumnName()));
                }
            }
        }

        if (!joins.isEmpty()) {
            for (int i = 0; i < joins.size(); i++) {
                data.append(joins.get(i));

                if (i < joins.size() - 1) {
                    data.append(" and ");
                }
            }
        }

        return data.toString();
    }

    private String translateLevel(br.com.bi.model.entity.metadata.Level level) {
        StringBuilder sb = new StringBuilder();

        sb.append(TranslationUtils.columnExpression(level.getTableName(), level.getCodeProperty().getColumnName()));

        return sb.toString();
    }

    private String translateProperty(br.com.bi.model.entity.metadata.Property property) {
        StringBuilder sb = new StringBuilder();

        sb.append(TranslationUtils.columnExpression(property.getLevel().getTableName(), property.getColumnName()));

        return sb.toString();
    }

    private void registrateAxisNode(SimpleNode node, Metadata metadata) {
        axisNodeMetadataMap.put(node, metadata);
        axisNodeList.add(node);
        axisNodeCoordinateMap.put(node, calculateCoordinates(node));
    }

    private String calculateCoordinates(SimpleNode node) {
        StringBuilder coordinate = new StringBuilder();

        for (int i = 0; i < nodeCoordinates.size(); i++) {
            if (i == 0) {
                if (nodeCoordinates.get(i) == 0) {
                    coordinate.append("r_");
                } else {
                    coordinate.append("c_");
                }
            } else {
                coordinate.append(nodeCoordinates.get(i)).append("_");
            }
        }

        coordinate.deleteCharAt(coordinate.length() - 1);

        return coordinate.toString();
    }
}
