/* Generated By:JJTree: Do not edit this line. MeasureExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.olapql.language.measure;

public
class MeasureExpression extends SimpleNode {
  public MeasureExpression(int id) {
    super(id);
  }

  public MeasureExpression(MeasureParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(MeasureParserVisitor visitor, StringBuilder data) {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5c600e59700c315d81ad7ebec0ff0dd0 (do not edit this line) */
