/* Generated By:JJTree: Do not edit this line. ASTMultiplication.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.proximati.biprime.server.olapql.language.measure;

public
class ASTMultiplication extends SimpleNode {
  public ASTMultiplication(int id) {
    super(id);
  }

  public ASTMultiplication(MeasureParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(MeasureParserVisitor visitor, StringBuilder data) throws Exception {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=08a366ae4de864c18cc778eefb0d468a (do not edit this line) */
