/* Generated By:JJTree: Do not edit this line. Comparison.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package br.com.bi.olapql.language.filter;

public
class Comparison extends SimpleNode {
  public Comparison(int id) {
    super(id);
  }

  public Comparison(FilterParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(FilterParserVisitor visitor, StringBuilder data) {
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0ca52eb2f41cb83c30c658fd79f8b6de (do not edit this line) */
